#ifndef __GUI_PACKETS_H__
#define __GUI_PACKETS_H__

#ifdef __cplusplus
extern "C" {
#endif

enum
{
  GUI_PACKET_NULL = 0,
  GUI_PACKET_LCD_HOME,
  GUI_PACKET_LCD_CLEAR,
  GUI_PACKET_LCD_PUT_STRING,
  GUI_PACKET_LCD_SET_CURSOR,
  GUI_PACKET_LCD_NO_DISPLAY,
  GUI_PACKET_LCD_DISPLAY,
  GUI_PACKET_LCD_NO_BLINK,
  GUI_PACKET_LCD_BLINK,
  GUI_PACKET_LCD_NO_CURSOR,
  GUI_PACKET_LCD_CURSOR,
  GUI_PACKET_LCD_SCROLL_DISPLAY_LEFT,
  GUI_PACKET_LCD_SCROLL_DISPLAY_RIGHT,
  GUI_PACKET_LCD_LEFT_TO_RIGHT,
  GUI_PACKET_LCD_RIGHT_TO_LEFT,
  GUI_PACKET_LCD_AUTOSCROLL,
  GUI_PACKET_LCD_NO_AUTOSCROLL,
  GUI_PACKET_KNOB_BUTTON,
  GUI_PACKET_KNOB_SELECT,
  GUI_PACKET_KNOB_DECREMENT,
  GUI_PACKET_KNOB_INCREMENT
};

#ifdef __cplusplus
}
#endif

#endif /* __GUI_PACKETS_H__ */
